# Generated by Django 3.2.7 on 2021-10-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
