# Generated by Django 3.2.7 on 2021-10-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_rename_update_at_place_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
